### ISSUE TITLE
Oracle Cloud Hosting

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/wiq_en1a#29]

**Comment by andrrsin** [comment]
In todays class, I came across a problem regarding the Oracle Machine, that is the Github Runner for the Action was ubuntu. This prevented the docker image to be composed. This has been solved making our own Oracle VM, a *self-hosted* Runner. This means now when editing the .yml files if we specify the following on the actions:
```yaml
runs-on: self-hosted
```
or as an alternative,
```yaml
runs-on: ARM64
```
The specified chunk of action will be then developed not by Github but our own VM, that you can see it created in Settings/Actions/Runners. This has been tested and it now works for the ssh deployment. However the docker files aren't composed yet. I would like to ask for some help @pglez82, maybe the problem is that I only do the task of ssh deploy and not only th ecreation of the docker files. You can see in GhActions the latest run and maybe we can get this working with you help.

Thanks in advanced, Andrés

**Comment by pglez82** [comment]
Yes. I think the docker images should be build for arm64, because that is the platform in which you are running it in production. Github actions is the one that builds the images, so you need to modify it accordingly (I tested this in my repository for the authservice):

```yml
docker-push-authservice:
    name: Push auth service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
          name: pglez82/asw2324_0/authservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: users/authservice
          platforms: linux/amd64,linux/arm64
```

This will build the arm images (as long with the amd64 images). That way when you pull the image in the Oracle machine, it will download the appropriate image for the arm architecture.

Let me know if you make it work.
